version: 1.0.{build}

os: unstable

environment:
  matrix:
  - QTDIR: C:\Qt\5.7\msvc2015_64

install:
  - set PATH=%QTDIR%\bin;%PATH%

configuration:
- Release

before_build:
  - cmake -H. -Bbuild -G "Visual Studio 14 2015 Win64" -DSARA_BUILD_VIDEOIO=ON -DSARA_BUILD_TESTS=ON -DSARA_BUILD_SAMPLES=ON

build_script:
  - '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" build\Sara.sln /m /verbosity:minimal'
