var namespace_d_o =
[
    [ "Meta", "namespace_d_o_1_1_meta.html", "namespace_d_o_1_1_meta" ],
    [ "R", "struct_d_o_1_1_r.html", null ],
    [ "G", "struct_d_o_1_1_g.html", null ],
    [ "B", "struct_d_o_1_1_b.html", null ],
    [ "A", "struct_d_o_1_1_a.html", null ],
    [ "C", "struct_d_o_1_1_c.html", null ],
    [ "M", "struct_d_o_1_1_m.html", null ],
    [ "Y", "struct_d_o_1_1_y.html", null ],
    [ "K", "struct_d_o_1_1_k.html", null ],
    [ "U", "struct_d_o_1_1_u.html", null ],
    [ "V", "struct_d_o_1_1_v.html", null ],
    [ "H", "struct_d_o_1_1_h.html", null ],
    [ "S", "struct_d_o_1_1_s.html", null ],
    [ "Gray", "struct_d_o_1_1_gray.html", null ],
    [ "Color", "class_d_o_1_1_color.html", "class_d_o_1_1_color" ],
    [ "ChannelTraits", "struct_d_o_1_1_channel_traits.html", "struct_d_o_1_1_channel_traits" ],
    [ "ColorTraits", "struct_d_o_1_1_color_traits.html", "struct_d_o_1_1_color_traits" ],
    [ "ColorTraits< Matrix< ChannelType_, M, N > >", "struct_d_o_1_1_color_traits_3_01_matrix_3_01_channel_type___00_01_m_00_01_n_01_4_01_4.html", "struct_d_o_1_1_color_traits_3_01_matrix_3_01_channel_type___00_01_m_00_01_n_01_4_01_4" ],
    [ "ColorTraits< uchar >", "struct_d_o_1_1_color_traits_3_01uchar_01_4.html", "struct_d_o_1_1_color_traits_3_01uchar_01_4" ],
    [ "ColorTraits< ushort >", "struct_d_o_1_1_color_traits_3_01ushort_01_4.html", "struct_d_o_1_1_color_traits_3_01ushort_01_4" ],
    [ "ColorTraits< uint >", "struct_d_o_1_1_color_traits_3_01uint_01_4.html", "struct_d_o_1_1_color_traits_3_01uint_01_4" ],
    [ "ColorTraits< char >", "struct_d_o_1_1_color_traits_3_01char_01_4.html", "struct_d_o_1_1_color_traits_3_01char_01_4" ],
    [ "ColorTraits< short >", "struct_d_o_1_1_color_traits_3_01short_01_4.html", "struct_d_o_1_1_color_traits_3_01short_01_4" ],
    [ "ColorTraits< int >", "struct_d_o_1_1_color_traits_3_01int_01_4.html", "struct_d_o_1_1_color_traits_3_01int_01_4" ],
    [ "ColorTraits< float >", "struct_d_o_1_1_color_traits_3_01float_01_4.html", "struct_d_o_1_1_color_traits_3_01float_01_4" ],
    [ "ColorTraits< double >", "struct_d_o_1_1_color_traits_3_01double_01_4.html", "struct_d_o_1_1_color_traits_3_01double_01_4" ],
    [ "LexicographicalOrder", "struct_d_o_1_1_lexicographical_order.html", "struct_d_o_1_1_lexicographical_order" ],
    [ "ElementTraits< Color< T, Layout > >", "struct_d_o_1_1_element_traits_3_01_color_3_01_t_00_01_layout_01_4_01_4.html", "struct_d_o_1_1_element_traits_3_01_color_3_01_t_00_01_layout_01_4_01_4" ],
    [ "Image", "class_d_o_1_1_image.html", "class_d_o_1_1_image" ],
    [ "ConvertImage", "struct_d_o_1_1_convert_image.html", null ],
    [ "ConvertImage< T, T, N >", "struct_d_o_1_1_convert_image_3_01_t_00_01_t_00_01_n_01_4.html", null ],
    [ "ColorRescale", "struct_d_o_1_1_color_rescale.html", "struct_d_o_1_1_color_rescale" ],
    [ "Offset", "struct_d_o_1_1_offset.html", null ],
    [ "Offset2", "struct_d_o_1_1_offset2.html", null ],
    [ "Offset< N, RowMajor >", "struct_d_o_1_1_offset_3_01_n_00_01_row_major_01_4.html", "struct_d_o_1_1_offset_3_01_n_00_01_row_major_01_4" ],
    [ "Offset< 1, RowMajor >", "struct_d_o_1_1_offset_3_011_00_01_row_major_01_4.html", null ],
    [ "Offset< N, ColMajor >", "struct_d_o_1_1_offset_3_01_n_00_01_col_major_01_4.html", "struct_d_o_1_1_offset_3_01_n_00_01_col_major_01_4" ],
    [ "Offset< 1, ColMajor >", "struct_d_o_1_1_offset_3_011_00_01_col_major_01_4.html", null ],
    [ "Offset2< 1 >", "struct_d_o_1_1_offset2_3_011_01_4.html", null ],
    [ "AxisIterator", "class_d_o_1_1_axis_iterator.html", "class_d_o_1_1_axis_iterator" ],
    [ "RangeIteratorBase", "class_d_o_1_1_range_iterator_base.html", "class_d_o_1_1_range_iterator_base" ],
    [ "RangeIterator", "class_d_o_1_1_range_iterator.html", "class_d_o_1_1_range_iterator" ],
    [ "SubrangeIterator", "class_d_o_1_1_subrange_iterator.html", "class_d_o_1_1_subrange_iterator" ],
    [ "CoordsIterator", "class_d_o_1_1_coords_iterator.html", "class_d_o_1_1_coords_iterator" ],
    [ "ElementTraits", "struct_d_o_1_1_element_traits.html", "struct_d_o_1_1_element_traits" ],
    [ "ElementTraits< Matrix< T, M, N > >", "struct_d_o_1_1_element_traits_3_01_matrix_3_01_t_00_01_m_00_01_n_01_4_01_4.html", "struct_d_o_1_1_element_traits_3_01_matrix_3_01_t_00_01_m_00_01_n_01_4_01_4" ],
    [ "ElementTraits< Array< T, M, N > >", "struct_d_o_1_1_element_traits_3_01_array_3_01_t_00_01_m_00_01_n_01_4_01_4.html", "struct_d_o_1_1_element_traits_3_01_array_3_01_t_00_01_m_00_01_n_01_4_01_4" ],
    [ "MultiArray", "class_d_o_1_1_multi_array.html", "class_d_o_1_1_multi_array" ],
    [ "SharedPointer", "class_d_o_1_1_shared_pointer.html", "class_d_o_1_1_shared_pointer" ],
    [ "SparseMultiArray", "class_d_o_1_1_sparse_multi_array.html", "class_d_o_1_1_sparse_multi_array" ],
    [ "Timer", "class_d_o_1_1_timer.html", "class_d_o_1_1_timer" ],
    [ "HighResTimer", "class_d_o_1_1_high_res_timer.html", "class_d_o_1_1_high_res_timer" ],
    [ "Tree", "class_d_o_1_1_tree.html", "class_d_o_1_1_tree" ],
    [ "AdaptFeatureAffinelyToLocalShape", "class_d_o_1_1_adapt_feature_affinely_to_local_shape.html", "class_d_o_1_1_adapt_feature_affinely_to_local_shape" ],
    [ "ComputeDoGExtrema", "class_d_o_1_1_compute_do_g_extrema.html", "class_d_o_1_1_compute_do_g_extrema" ],
    [ "DoGSiftDetector", "class_d_o_1_1_do_g_sift_detector.html", "class_d_o_1_1_do_g_sift_detector" ],
    [ "HarAffSiftDetector", "class_d_o_1_1_har_aff_sift_detector.html", "class_d_o_1_1_har_aff_sift_detector" ],
    [ "ComputeHarrisLaplaceCorners", "class_d_o_1_1_compute_harris_laplace_corners.html", "class_d_o_1_1_compute_harris_laplace_corners" ],
    [ "HesAffSiftDetector", "class_d_o_1_1_hes_aff_sift_detector.html", "class_d_o_1_1_hes_aff_sift_detector" ],
    [ "MserSiftDetector", "class_d_o_1_1_mser_sift_detector.html", "class_d_o_1_1_mser_sift_detector" ],
    [ "ComputeDominantOrientations", "class_d_o_1_1_compute_dominant_orientations.html", "class_d_o_1_1_compute_dominant_orientations" ],
    [ "ComputeSIFTDescriptor", "class_d_o_1_1_compute_s_i_f_t_descriptor.html", "class_d_o_1_1_compute_s_i_f_t_descriptor" ],
    [ "DescriptorBase", "class_d_o_1_1_descriptor_base.html", "class_d_o_1_1_descriptor_base" ],
    [ "Descriptor", "class_d_o_1_1_descriptor.html", "class_d_o_1_1_descriptor" ],
    [ "Feature", "class_d_o_1_1_feature.html", "class_d_o_1_1_feature" ],
    [ "PointFeature", "class_d_o_1_1_point_feature.html", "class_d_o_1_1_point_feature" ],
    [ "OERegion", "class_d_o_1_1_o_e_region.html", "class_d_o_1_1_o_e_region" ],
    [ "FeatureItemSelector", "struct_d_o_1_1_feature_item_selector.html", [
      [ "FeatureItem", "class_d_o_1_1_feature_item_selector_1_1_feature_item.html", "class_d_o_1_1_feature_item_selector_1_1_feature_item" ],
      [ "MatchItem", "class_d_o_1_1_feature_item_selector_1_1_match_item.html", "class_d_o_1_1_feature_item_selector_1_1_match_item" ]
    ] ],
    [ "Key", "class_d_o_1_1_key.html", "class_d_o_1_1_key" ],
    [ "KeyRef", "struct_d_o_1_1_key_ref.html", "struct_d_o_1_1_key_ref" ],
    [ "ImageFeaturesItem", "class_d_o_1_1_image_features_item.html", "class_d_o_1_1_image_features_item" ],
    [ "BBox", "struct_d_o_1_1_b_box.html", "struct_d_o_1_1_b_box" ],
    [ "Ellipse", "class_d_o_1_1_ellipse.html", "class_d_o_1_1_ellipse" ],
    [ "SquaredRefDistance", "class_d_o_1_1_squared_ref_distance.html", "class_d_o_1_1_squared_ref_distance" ],
    [ "SquaredDistance", "class_d_o_1_1_squared_distance.html", "class_d_o_1_1_squared_distance" ],
    [ "OpenBall", "class_d_o_1_1_open_ball.html", "class_d_o_1_1_open_ball" ],
    [ "Quad", "struct_d_o_1_1_quad.html", "struct_d_o_1_1_quad" ],
    [ "Triangle", "class_d_o_1_1_triangle.html", "class_d_o_1_1_triangle" ],
    [ "TriangleFlatness", "class_d_o_1_1_triangle_flatness.html", "class_d_o_1_1_triangle_flatness" ],
    [ "InteractiveBox", "struct_d_o_1_1_interactive_box.html", "struct_d_o_1_1_interactive_box" ],
    [ "GraphicsApplication", "class_d_o_1_1_graphics_application.html", "class_d_o_1_1_graphics_application" ],
    [ "GraphicsView", "class_d_o_1_1_graphics_view.html", "class_d_o_1_1_graphics_view" ],
    [ "TrackBall", "class_d_o_1_1_track_ball.html", "class_d_o_1_1_track_ball" ],
    [ "OpenGLWindow", "class_d_o_1_1_open_g_l_window.html", "class_d_o_1_1_open_g_l_window" ],
    [ "ScrollArea", "class_d_o_1_1_scroll_area.html", "class_d_o_1_1_scroll_area" ],
    [ "PaintingWindow", "class_d_o_1_1_painting_window.html", "class_d_o_1_1_painting_window" ],
    [ "PixmapItem", "class_d_o_1_1_pixmap_item.html", "class_d_o_1_1_pixmap_item" ],
    [ "UserThread", "class_d_o_1_1_user_thread.html", "class_d_o_1_1_user_thread" ],
    [ "Event", "struct_d_o_1_1_event.html", "struct_d_o_1_1_event" ],
    [ "SimpleMesh", "class_d_o_1_1_simple_mesh.html", "class_d_o_1_1_simple_mesh" ],
    [ "MeshReader", "class_d_o_1_1_mesh_reader.html", "class_d_o_1_1_mesh_reader" ],
    [ "DericheBlur", "struct_d_o_1_1_deriche_blur.html", "struct_d_o_1_1_deriche_blur" ],
    [ "Determinant", "struct_d_o_1_1_determinant.html", "struct_d_o_1_1_determinant" ],
    [ "Differential", "struct_d_o_1_1_differential.html", "struct_d_o_1_1_differential" ],
    [ "Differential< N, 0 >", "struct_d_o_1_1_differential_3_01_n_00_010_01_4.html", null ],
    [ "Gradient", "struct_d_o_1_1_gradient.html", "struct_d_o_1_1_gradient" ],
    [ "Laplacian", "struct_d_o_1_1_laplacian.html", "struct_d_o_1_1_laplacian" ],
    [ "Hessian", "struct_d_o_1_1_hessian.html", "struct_d_o_1_1_hessian" ],
    [ "CompareWithNeighborhood3", "struct_d_o_1_1_compare_with_neighborhood3.html", "struct_d_o_1_1_compare_with_neighborhood3" ],
    [ "LocalExtremum", "struct_d_o_1_1_local_extremum.html", "struct_d_o_1_1_local_extremum" ],
    [ "LocalScaleSpaceExtremum", "struct_d_o_1_1_local_scale_space_extremum.html", "struct_d_o_1_1_local_scale_space_extremum" ],
    [ "LocalMax", "struct_d_o_1_1_local_max.html", null ],
    [ "LocalMin", "struct_d_o_1_1_local_min.html", null ],
    [ "LocalScaleSpaceMax", "struct_d_o_1_1_local_scale_space_max.html", null ],
    [ "LocalScaleSpaceMin", "struct_d_o_1_1_local_scale_space_min.html", null ],
    [ "StrictLocalMax", "struct_d_o_1_1_strict_local_max.html", null ],
    [ "StrictLocalMin", "struct_d_o_1_1_strict_local_min.html", null ],
    [ "StrictLocalScaleSpaceMax", "struct_d_o_1_1_strict_local_scale_space_max.html", null ],
    [ "StrictLocalScaleSpaceMin", "struct_d_o_1_1_strict_local_scale_space_min.html", null ],
    [ "ImagePyramidParams", "class_d_o_1_1_image_pyramid_params.html", "class_d_o_1_1_image_pyramid_params" ],
    [ "ImagePyramid", "class_d_o_1_1_image_pyramid.html", "class_d_o_1_1_image_pyramid" ],
    [ "Sobel", "struct_d_o_1_1_sobel.html", null ],
    [ "Sobel< T, 2 >", "struct_d_o_1_1_sobel_3_01_t_00_012_01_4.html", "struct_d_o_1_1_sobel_3_01_t_00_012_01_4" ],
    [ "Scharr", "struct_d_o_1_1_scharr.html", null ],
    [ "Scharr< T, 2 >", "struct_d_o_1_1_scharr_3_01_t_00_012_01_4.html", "struct_d_o_1_1_scharr_3_01_t_00_012_01_4" ],
    [ "Prewitt", "struct_d_o_1_1_prewitt.html", null ],
    [ "Prewitt< T, 2 >", "struct_d_o_1_1_prewitt_3_01_t_00_012_01_4.html", "struct_d_o_1_1_prewitt_3_01_t_00_012_01_4" ],
    [ "RobertsCross", "struct_d_o_1_1_roberts_cross.html", null ],
    [ "RobertsCross< T, 2 >", "struct_d_o_1_1_roberts_cross_3_01_t_00_012_01_4.html", "struct_d_o_1_1_roberts_cross_3_01_t_00_012_01_4" ],
    [ "Robinson", "struct_d_o_1_1_robinson.html", null ],
    [ "Robinson< T, 2 >", "struct_d_o_1_1_robinson_3_01_t_00_012_01_4.html", "struct_d_o_1_1_robinson_3_01_t_00_012_01_4" ],
    [ "Kirsch", "struct_d_o_1_1_kirsch.html", null ],
    [ "Kirsch< T, 2 >", "struct_d_o_1_1_kirsch_3_01_t_00_012_01_4.html", "struct_d_o_1_1_kirsch_3_01_t_00_012_01_4" ],
    [ "Gaussian", "struct_d_o_1_1_gaussian.html", null ],
    [ "Gaussian< T, 2 >", "struct_d_o_1_1_gaussian_3_01_t_00_012_01_4.html", "struct_d_o_1_1_gaussian_3_01_t_00_012_01_4" ],
    [ "SquaredNorm", "struct_d_o_1_1_squared_norm.html", "struct_d_o_1_1_squared_norm" ],
    [ "BlueNorm", "struct_d_o_1_1_blue_norm.html", "struct_d_o_1_1_blue_norm" ],
    [ "StableNorm", "struct_d_o_1_1_stable_norm.html", "struct_d_o_1_1_stable_norm" ],
    [ "Orientation", "struct_d_o_1_1_orientation.html", null ],
    [ "Orientation< T, 2 >", "struct_d_o_1_1_orientation_3_01_t_00_012_01_4.html", "struct_d_o_1_1_orientation_3_01_t_00_012_01_4" ],
    [ "SecondMomentMatrix", "struct_d_o_1_1_second_moment_matrix.html", "struct_d_o_1_1_second_moment_matrix" ]
];