var searchData=
[
  ['s',['S',['../struct_d_o_1_1_sara_1_1_s.html',1,'DO::Sara']]],
  ['scharr',['Scharr',['../struct_d_o_1_1_sara_1_1_scharr.html',1,'DO::Sara']]],
  ['scrollarea',['ScrollArea',['../class_d_o_1_1_sara_1_1_scroll_area.html',1,'DO::Sara']]],
  ['secondmomentmatrix',['SecondMomentMatrix',['../struct_d_o_1_1_sara_1_1_second_moment_matrix.html',1,'DO::Sara']]],
  ['set',['Set',['../class_d_o_1_1_sara_1_1_set.html',1,'DO::Sara']]],
  ['simplemesh',['SimpleMesh',['../class_d_o_1_1_sara_1_1_simple_mesh.html',1,'DO::Sara']]],
  ['simplemesh_3c_20point3f_2c_20face3_20_3e',['SimpleMesh&lt; Point3f, Face3 &gt;',['../class_d_o_1_1_sara_1_1_simple_mesh.html',1,'DO::Sara']]],
  ['singleton',['Singleton',['../class_d_o_1_1_sara_1_1_c_s_g_1_1_singleton.html',1,'DO::Sara::CSG']]],
  ['smallpolygon',['SmallPolygon',['../class_d_o_1_1_sara_1_1_small_polygon.html',1,'DO::Sara']]],
  ['smallpolygon_3c_203_20_3e',['SmallPolygon&lt; 3 &gt;',['../class_d_o_1_1_sara_1_1_small_polygon.html',1,'DO::Sara']]],
  ['smallpolygon_3c_204_20_3e',['SmallPolygon&lt; 4 &gt;',['../class_d_o_1_1_sara_1_1_small_polygon.html',1,'DO::Sara']]],
  ['smartconvertcolor',['SmartConvertColor',['../struct_d_o_1_1_sara_1_1_detail_1_1_smart_convert_color.html',1,'DO::Sara::Detail']]],
  ['smartconvertcolor_3c_20colspace_2c_20colspace_20_3e',['SmartConvertColor&lt; ColSpace, ColSpace &gt;',['../struct_d_o_1_1_sara_1_1_detail_1_1_smart_convert_color_3_01_col_space_00_01_col_space_01_4.html',1,'DO::Sara::Detail']]],
  ['sobel',['Sobel',['../struct_d_o_1_1_sara_1_1_sobel.html',1,'DO::Sara']]],
  ['sparsemultiarray',['SparseMultiArray',['../class_d_o_1_1_sara_1_1_sparse_multi_array.html',1,'DO::Sara']]],
  ['sphere',['Sphere',['../class_d_o_1_1_sara_1_1_sphere.html',1,'DO::Sara']]],
  ['squareddistance',['SquaredDistance',['../class_d_o_1_1_sara_1_1_squared_distance.html',1,'DO::Sara']]],
  ['squarednorm',['SquaredNorm',['../struct_d_o_1_1_sara_1_1_squared_norm.html',1,'DO::Sara']]],
  ['squaredrefdistance',['SquaredRefDistance',['../class_d_o_1_1_sara_1_1_squared_ref_distance.html',1,'DO::Sara']]],
  ['stablenorm',['StableNorm',['../struct_d_o_1_1_sara_1_1_stable_norm.html',1,'DO::Sara']]],
  ['strictlocalmax',['StrictLocalMax',['../struct_d_o_1_1_sara_1_1_strict_local_max.html',1,'DO::Sara']]],
  ['strictlocalmin',['StrictLocalMin',['../struct_d_o_1_1_sara_1_1_strict_local_min.html',1,'DO::Sara']]],
  ['strictlocalscalespacemax',['StrictLocalScaleSpaceMax',['../struct_d_o_1_1_sara_1_1_strict_local_scale_space_max.html',1,'DO::Sara']]],
  ['strictlocalscalespacemin',['StrictLocalScaleSpaceMin',['../struct_d_o_1_1_sara_1_1_strict_local_scale_space_min.html',1,'DO::Sara']]],
  ['stridecomputer',['StrideComputer',['../struct_d_o_1_1_sara_1_1_stride_computer.html',1,'DO::Sara']]],
  ['stridecomputer_3c_20colmajor_20_3e',['StrideComputer&lt; ColMajor &gt;',['../struct_d_o_1_1_sara_1_1_stride_computer_3_01_col_major_01_4.html',1,'DO::Sara']]],
  ['stridecomputer_3c_20rowmajor_20_3e',['StrideComputer&lt; RowMajor &gt;',['../struct_d_o_1_1_sara_1_1_stride_computer_3_01_row_major_01_4.html',1,'DO::Sara']]],
  ['subarrayiterator',['SubarrayIterator',['../class_d_o_1_1_sara_1_1_subarray_iterator.html',1,'DO::Sara']]]
];
