var searchData=
[
  ['c',['C',['../struct_d_o_1_1_c.html',1,'DO']]],
  ['channeltraits',['ChannelTraits',['../struct_d_o_1_1_channel_traits.html',1,'DO']]],
  ['choose',['Choose',['../struct_d_o_1_1_meta_1_1_choose.html',1,'DO::Meta']]],
  ['choose_3c_20false_2c_20istrue_2c_20isfalse_20_3e',['Choose&lt; false, IsTrue, IsFalse &gt;',['../struct_d_o_1_1_meta_1_1_choose_3_01false_00_01_is_true_00_01_is_false_01_4.html',1,'DO::Meta']]],
  ['choose_3c_20isconst_2c_20const_20node_20_2a_2c_20node_20_2a_20_3e',['Choose&lt; IsConst, const Node *, Node * &gt;',['../struct_d_o_1_1_meta_1_1_choose.html',1,'DO::Meta']]],
  ['choose_3c_20true_2c_20istrue_2c_20isfalse_20_3e',['Choose&lt; true, IsTrue, IsFalse &gt;',['../struct_d_o_1_1_meta_1_1_choose_3_01true_00_01_is_true_00_01_is_false_01_4.html',1,'DO::Meta']]],
  ['color',['Color',['../class_d_o_1_1_color.html',1,'DO']]],
  ['colorrescale',['ColorRescale',['../struct_d_o_1_1_color_rescale.html',1,'DO']]],
  ['colortraits',['ColorTraits',['../struct_d_o_1_1_color_traits.html',1,'DO']]],
  ['colortraits_3c_20char_20_3e',['ColorTraits&lt; char &gt;',['../struct_d_o_1_1_color_traits_3_01char_01_4.html',1,'DO']]],
  ['colortraits_3c_20color_20_3e',['ColorTraits&lt; Color &gt;',['../struct_d_o_1_1_color_traits.html',1,'DO']]],
  ['colortraits_3c_20double_20_3e',['ColorTraits&lt; double &gt;',['../struct_d_o_1_1_color_traits_3_01double_01_4.html',1,'DO']]],
  ['colortraits_3c_20float_20_3e',['ColorTraits&lt; float &gt;',['../struct_d_o_1_1_color_traits_3_01float_01_4.html',1,'DO']]],
  ['colortraits_3c_20int_20_3e',['ColorTraits&lt; int &gt;',['../struct_d_o_1_1_color_traits_3_01int_01_4.html',1,'DO']]],
  ['colortraits_3c_20matrix_3c_20channeltype_5f_2c_20m_2c_20n_20_3e_20_3e',['ColorTraits&lt; Matrix&lt; ChannelType_, M, N &gt; &gt;',['../struct_d_o_1_1_color_traits_3_01_matrix_3_01_channel_type___00_01_m_00_01_n_01_4_01_4.html',1,'DO']]],
  ['colortraits_3c_20short_20_3e',['ColorTraits&lt; short &gt;',['../struct_d_o_1_1_color_traits_3_01short_01_4.html',1,'DO']]],
  ['colortraits_3c_20uchar_20_3e',['ColorTraits&lt; uchar &gt;',['../struct_d_o_1_1_color_traits_3_01uchar_01_4.html',1,'DO']]],
  ['colortraits_3c_20uint_20_3e',['ColorTraits&lt; uint &gt;',['../struct_d_o_1_1_color_traits_3_01uint_01_4.html',1,'DO']]],
  ['colortraits_3c_20ushort_20_3e',['ColorTraits&lt; ushort &gt;',['../struct_d_o_1_1_color_traits_3_01ushort_01_4.html',1,'DO']]],
  ['comparewithneighborhood3',['CompareWithNeighborhood3',['../struct_d_o_1_1_compare_with_neighborhood3.html',1,'DO']]],
  ['comparewithneighborhood3_3c_20std_3a_3agreater_2c_20t_20_3e',['CompareWithNeighborhood3&lt; std::greater, T &gt;',['../struct_d_o_1_1_compare_with_neighborhood3.html',1,'DO']]],
  ['comparewithneighborhood3_3c_20std_3a_3agreater_5fequal_2c_20t_20_3e',['CompareWithNeighborhood3&lt; std::greater_equal, T &gt;',['../struct_d_o_1_1_compare_with_neighborhood3.html',1,'DO']]],
  ['comparewithneighborhood3_3c_20std_3a_3aless_2c_20t_20_3e',['CompareWithNeighborhood3&lt; std::less, T &gt;',['../struct_d_o_1_1_compare_with_neighborhood3.html',1,'DO']]],
  ['comparewithneighborhood3_3c_20std_3a_3aless_5fequal_2c_20t_20_3e',['CompareWithNeighborhood3&lt; std::less_equal, T &gt;',['../struct_d_o_1_1_compare_with_neighborhood3.html',1,'DO']]],
  ['computedogextrema',['ComputeDoGExtrema',['../class_d_o_1_1_compute_do_g_extrema.html',1,'DO']]],
  ['computedominantorientations',['ComputeDominantOrientations',['../class_d_o_1_1_compute_dominant_orientations.html',1,'DO']]],
  ['computeharrislaplacecorners',['ComputeHarrisLaplaceCorners',['../class_d_o_1_1_compute_harris_laplace_corners.html',1,'DO']]],
  ['computesiftdescriptor',['ComputeSIFTDescriptor',['../class_d_o_1_1_compute_s_i_f_t_descriptor.html',1,'DO']]],
  ['convertimage',['ConvertImage',['../struct_d_o_1_1_convert_image.html',1,'DO']]],
  ['convertimage_3c_20t_2c_20t_2c_20n_20_3e',['ConvertImage&lt; T, T, N &gt;',['../struct_d_o_1_1_convert_image_3_01_t_00_01_t_00_01_n_01_4.html',1,'DO']]],
  ['coordsiterator',['CoordsIterator',['../class_d_o_1_1_coords_iterator.html',1,'DO']]]
];
